name: mfsim_assistente
description: Assistente Virtual MFSim - Flutter UI
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  google_fonts: ^6.1.0
  animated_text_kit: ^4.2.2
  flutter_spinkit: ^5.2.0
  flutter_markdown: ^0.7.2
  provider: ^6.1.5+1
  url_launcher: ^6.2.5
  path_provider: ^2.1.2
  open_filex: ^4.4.0
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_libs_windows_video: ^1.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  shared_preferences: ^2.2.2
  uuid: ^4.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/robot_mfsim.png